# Generated by Django 4.2.15 on 2026-08-21 18:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0015_groupmatch_proposed_at_groupmatch_proposed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scoreboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Адрес плашки: /scoreboard/overlay?board=<key>', max_length=40, unique=True)),
                ('title', models.CharField(blank=True, default='', help_text='Например «Стол 3»', max_length=60)),
                ('table_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rev', models.PositiveIntegerField(default=0)),
                ('match_label', models.CharField(blank=True, default='MT', max_length=12)),
                ('round_label', models.CharField(blank=True, default='R 16', max_length=16)),
                ('best_of', models.PositiveSmallIntegerField(choices=[(5, 'До 3 побед'), (7, 'До 4 побед')], default=5)),
                ('status_lang', models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], default='en', max_length=2)),
                ('status_override', models.CharField(blank=True, default=None, max_length=24, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('left_name', models.CharField(blank=True, default='', max_length=40)),
                ('left_country', models.CharField(blank=True, default='', max_length=3)),
                ('left_games', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9)])),
                ('left_points', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99)])),
                ('right_name', models.CharField(blank=True, default='', max_length=40)),
                ('right_country', models.CharField(blank=True, default='', max_length=3)),
                ('right_games', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9)])),
                ('right_points', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99)])),
                ('team_enabled', models.BooleanField(default=False)),
                ('team_left', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9)])),
                ('team_right', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoreboards', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['key'],
                'indexes': [models.Index(fields=['tournament', 'table_number'], name='scoreboard__tournam_281334_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='scoreboard',
            constraint=models.UniqueConstraint(condition=models.Q(('table_number__isnull', False), ('tournament__isnull', False)), fields=('tournament', 'table_number'), name='uniq_scoreboard_per_tournament_table'),
        ),
    ]
