# Generated by Django 4.2.15 on 2026-08-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='first_server',
            field=models.CharField(blank=True, choices=[('', 'Не задан'), ('left1', 'Слева, первый'), ('left2', 'Слева, второй'), ('right1', 'Справа, первый'), ('right2', 'Справа, второй')], default='', max_length=6),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='left_card',
            field=models.CharField(blank=True, choices=[('', 'Нет'), ('yellow', 'Жёлтая'), ('red', 'Красная')], default='', max_length=6),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='left_name2',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='left_timeout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='right_card',
            field=models.CharField(blank=True, choices=[('', 'Нет'), ('yellow', 'Жёлтая'), ('red', 'Красная')], default='', max_length=6),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='right_name2',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='right_timeout',
            field=models.BooleanField(default=False),
        ),
    ]
