# Generated by Django 4.2.15 on 2026-05-26 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('in_progress', 'В процессе'), ('finished', 'Завершён')], default='open', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(verbose_name='Раунд')),
                ('match_number', models.PositiveIntegerField(verbose_name='Номер матча')),
                ('score1', models.PositiveIntegerField(blank=True, null=True, verbose_name='Счёт игрока 1')),
                ('score2', models.PositiveIntegerField(blank=True, null=True, verbose_name='Счёт игрока 2')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('in_progress', 'Идёт'), ('finished', 'Завершён')], default='pending', max_length=20, verbose_name='Статус')),
                ('player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_player1', to=settings.AUTH_USER_MODEL, verbose_name='Игрок 1')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_player2', to=settings.AUTH_USER_MODEL, verbose_name='Игрок 2')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament', verbose_name='Турнир')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to=settings.AUTH_USER_MODEL, verbose_name='Победитель')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'ordering': ['round_number', 'match_number'],
                'unique_together': {('tournament', 'round_number', 'match_number')},
            },
        ),
    ]
