# Generated by Django 4.2.15 on 2026-05-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_status_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='table_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Стол'),
        ),
    ]
