# Generated by Django 4.2.15 on 2026-05-27 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_tournament_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='tournaments.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Стол',
                'verbose_name_plural': 'Столы',
                'ordering': ['number'],
                'unique_together': {('tournament', 'number')},
            },
        ),
    ]
