# Generated by Django 4.2.15 on 2026-05-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournament_format_tournament_group_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmatch',
            name='table_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Стол'),
        ),
    ]
