# Generated by Django 4.2.15 on 2026-05-28 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_groupmatch_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_consolation',
            field=models.BooleanField(default=False, verbose_name='Утешительный'),
        ),
        migrations.AddField(
            model_name='match',
            name='loser_next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.match', verbose_name='Следующий матч проигравшего'),
        ),
        migrations.AddField(
            model_name='match',
            name='loser_next_slot',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
