# Generated by Django 4.2.15 on 2026-05-28 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_match_is_consolation_match_loser_next_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='winner_next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.match', verbose_name='Следующий матч победителя'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner_next_slot',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
