# Generated by Django 4.2.15 on 2026-05-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_match_winner_next_match_winner_next_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='place_hi',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Место до'),
        ),
        migrations.AddField(
            model_name='match',
            name='place_lo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Место от'),
        ),
    ]
