# Generated by Django 4.2.15 on 2026-05-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_match_place_hi_match_place_lo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentparticipant',
            name='rating_before',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рейтинг до'),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='rating_change',
            field=models.IntegerField(blank=True, null=True, verbose_name='Изменение рейтинга'),
        ),
    ]
