# Generated by Django 4.2.15 on 2026-05-31 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0011_tournamentparticipant_rating_before_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_by_name', models.CharField(blank=True, max_length=150)),
                ('kind', models.CharField(max_length=12)),
                ('match_label', models.CharField(blank=True, max_length=80)),
                ('player1_name', models.CharField(blank=True, max_length=150)),
                ('player2_name', models.CharField(blank=True, max_length=150)),
                ('score1', models.IntegerField(blank=True, null=True)),
                ('score2', models.IntegerField(blank=True, null=True)),
                ('winner_name', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(default='score', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_logs', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
