# Generated by Django 4.2.15 on 2026-06-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_scorelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmatch',
            name='is_walkover',
            field=models.BooleanField(default=False, verbose_name='Неявка'),
        ),
        migrations.AddField(
            model_name='groupparticipant',
            name='seed',
            field=models.PositiveIntegerField(default=0, verbose_name='Посев'),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='is_absent',
            field=models.BooleanField(default=False, verbose_name='Отсутствует'),
        ),
    ]
