# Generated by Django 4.2.15 on 2026-06-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_groupmatch_is_walkover_groupparticipant_seed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_walkover',
            field=models.BooleanField(default=False, verbose_name='Неявка'),
        ),
    ]
