# Generated by Django 4.2.15 on 2026-06-01 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0014_match_is_walkover'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmatch',
            name='proposed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmatch',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gm_proposed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmatch',
            name='proposed_score1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmatch',
            name='proposed_score2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmatch',
            name='proposed_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gm_proposed_won', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='proposed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_proposed', to=settings.AUTH_USER_MODEL, verbose_name='Счёт предложил'),
        ),
        migrations.AddField(
            model_name='match',
            name='proposed_score1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='proposed_score2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='proposed_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_proposed_won', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupmatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('in_progress', 'Идёт'), ('score_proposed', 'Ожидает подтверждения'), ('finished', 'Завершён')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('in_progress', 'Идёт'), ('score_proposed', 'Ожидает подтверждения'), ('finished', 'Завершён')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
