# Generated by Django 4.2.15 on 2026-09-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_groupmatch_proposed_at_groupmatch_proposed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_rating',
            field=models.BooleanField(default=True, verbose_name='Рейтинговый турнир'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='level',
            field=models.CharField(choices=[('top', 'Чемпионат и кубок РК, спартакиада, молодёжные игры, ТОП-12'), ('republic', 'Чемпионаты РК по возрастам, ЕЛНТ, республиканские'), ('region', 'Областные и городские'), ('amateur', 'Любительские турниры')], default='republic', max_length=16, verbose_name='Уровень соревнования (п. 13)'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='no_third_place_match',
            field=models.BooleanField(default=False, verbose_name='Матча за 3-е место не было (п. 10.4)'),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='place',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Итоговое место'),
        ),
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='rating_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Рейтинг до'),
        ),
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='rating_change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Изменение рейтинга'),
        ),
    ]
