# Generated by Django 4.2.15 on 2026-09-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0016_tournament_is_rating_tournament_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('single_elimination', 'Олимпийская система'), ('group_playoff', 'Групповой этап + плей-офф'), ('manual', 'Протокол вручную')], default='single_elimination', max_length=30, verbose_name='Формат'),
        ),
    ]
