# Generated by Django 4.2.15 on 2026-09-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0017_manual_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='games_to_win',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Партий до победы в матче'),
        ),
    ]
