# Generated by Django 4.2.15 on 2026-09-15 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0018_games_to_win'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentAgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, verbose_name='Название')),
                ('born_from', models.DateField(verbose_name='Дата рождения от')),
                ('born_to', models.DateField(verbose_name='Дата рождения до')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_categories', to='tournaments.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Возрастная категория',
                'verbose_name_plural': 'Возрастные категории',
                'ordering': ['order', 'id'],
            },
        ),
    ]
