from django.urls import path
from .views import (
    AddParticipantView,
    AssignTableView,
    GroupListView,
    GroupMatchResetView,
    GroupMatchScoreView,
    GroupMatchTableView,
    MatchListView,
    MatchResetView,
    MyTournamentsView,
    RegisterAndJoinView,
    RemoveParticipantView,
    StartPlayoffView,
    StartTournamentView,
    SubmitScoreView,
    TournamentDetailView,
    TournamentJoinView,
    TournamentListCreateView,
    TournamentParticipantsView,
    TournamentTableDetailView,
    TournamentTableListCreateView,
    TournamentUpdateDeleteView,
)

urlpatterns = [
    path("", TournamentListCreateView.as_view(), name="tournament-list-create"),
    path("my/", MyTournamentsView.as_view(), name="tournament-my"),
    path("<uuid:pk>/", TournamentDetailView.as_view(), name="tournament-detail"),
    path("<uuid:pk>/update/", TournamentUpdateDeleteView.as_view(), name="tournament-update-delete"),
    path("<uuid:pk>/participants/", TournamentParticipantsView.as_view(), name="tournament-participants"),
    path("<uuid:pk>/participants/add/", AddParticipantView.as_view(), name="tournament-add-participant"),
    path("<uuid:pk>/participants/<int:participant_id>/remove/", RemoveParticipantView.as_view(), name="tournament-remove-participant"),
    path("<uuid:pk>/start/", StartTournamentView.as_view(), name="tournament-start"),
    path("<uuid:pk>/matches/", MatchListView.as_view(), name="tournament-matches"),
    path("<uuid:pk>/matches/<int:match_id>/score/", SubmitScoreView.as_view(), name="tournament-score"),
    path("<uuid:pk>/matches/<int:match_id>/reset/", MatchResetView.as_view(), name="tournament-match-reset"),
    path("<uuid:pk>/matches/<int:match_id>/table/", AssignTableView.as_view(), name="tournament-assign-table"),
    path("<uuid:pk>/tables/", TournamentTableListCreateView.as_view(), name="tournament-tables"),
    path("<uuid:pk>/tables/<int:table_id>/", TournamentTableDetailView.as_view(), name="tournament-table-detail"),
    path("<uuid:pk>/groups/", GroupListView.as_view(), name="tournament-groups"),
    path("<uuid:pk>/groups/<int:group_id>/matches/<int:match_id>/score/", GroupMatchScoreView.as_view(), name="tournament-group-match-score"),
    path("<uuid:pk>/groups/<int:group_id>/matches/<int:match_id>/reset/", GroupMatchResetView.as_view(), name="tournament-group-match-reset"),
    path("<uuid:pk>/groups/<int:group_id>/matches/<int:match_id>/table/", GroupMatchTableView.as_view(), name="tournament-group-match-table"),
    path("<uuid:pk>/playoff/", StartPlayoffView.as_view(), name="tournament-playoff"),
    path("join/<uuid:join_token>/", TournamentJoinView.as_view(), name="tournament-join"),
    path("join/<uuid:join_token>/register/", RegisterAndJoinView.as_view(), name="tournament-register-join"),
]
