# Generated by Django 4.2.15 on 2026-05-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='club_photos/'),
        ),
    ]
