# Generated by Django 4.2.15 on 2026-09-09 19:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0016_tournament_is_rating_tournament_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Текущий рейтинг')),
                ('origin', models.CharField(choices=[('new', 'Новый — 1,00 (п. 6.1)'), ('legacy', 'Перенос прежнего (п. 6.3)'), ('ittf', 'Из позиции ITTF (п. 17)')], default='new', max_length=10, verbose_name='Происхождение стартового значения')),
                ('start_value', models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Стартовое значение')),
                ('ittf_position', models.PositiveIntegerField(blank=True, null=True, verbose_name='Позиция в ITTF World Ranking')),
                ('matches_played', models.PositiveIntegerField(default=0, verbose_name='Рейтинговых матчей')),
                ('wins', models.PositiveIntegerField(default=0, verbose_name='Побед')),
                ('losses', models.PositiveIntegerField(default=0, verbose_name='Поражений')),
                ('no_shows', models.PositiveIntegerField(default=0, verbose_name='Подтверждённых неявок')),
                ('last_match_at', models.DateField(blank=True, null=True, verbose_name='Последний рейтинговый матч')),
                ('status', models.CharField(choices=[('no_matches', 'Нет матчей'), ('active', 'Активен'), ('inactive', 'Неактивен'), ('void', 'Рейтинг аннулирован')], default='no_matches', max_length=12, verbose_name='Статус')),
                ('sex', models.CharField(blank=True, choices=[('m', 'Мужской'), ('f', 'Женский')], max_length=1, verbose_name='Пол')),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год рождения')),
                ('region', models.CharField(blank=True, max_length=120, verbose_name='Регион')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рейтинговая карточка',
                'verbose_name_plural': 'Рейтинговые карточки',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='RatingParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Действующий набор', max_length=120, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующий')),
                ('d', models.DecimalField(decimal_places=2, default=15, max_digits=6, verbose_name='D — масштаб шкалы (п. 9.4)')),
                ('k_standard', models.DecimalField(decimal_places=3, default=0.6, max_digits=6, verbose_name='K стандартный, с 21-го матча (п. 11.4)')),
                ('k_transition', models.DecimalField(decimal_places=3, default=3, max_digits=6, verbose_name='K переходного периода (п. 11.2)')),
                ('max_delta', models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Потолок изменения за матч, 0 — без потолка (п. 12.1)')),
                ('cap_in_transition', models.BooleanField(default=False, verbose_name='Резать потолком и переходный период')),
                ('ittf_r_max', models.DecimalField(decimal_places=2, default=90, max_digits=6, verbose_name='Rmax перевода из ITTF (п. 17.4)')),
                ('ittf_k', models.DecimalField(decimal_places=2, default=10, max_digits=6, verbose_name='k перевода из ITTF (п. 17.4)')),
                ('transition_matches', models.PositiveIntegerField(default=20, verbose_name='Длина переходного периода, матчей (п. 11.2–11.3)')),
                ('c_top', models.DecimalField(decimal_places=2, default=1.2, max_digits=4, verbose_name='C · высшие (п. 13)')),
                ('c_republic', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='C · республиканские')),
                ('c_region', models.DecimalField(decimal_places=2, default=0.8, max_digits=4, verbose_name='C · областные')),
                ('c_amateur', models.DecimalField(decimal_places=2, default=0.6, max_digits=4, verbose_name='C · любительские')),
                ('p_first', models.DecimalField(decimal_places=2, default=1.2, max_digits=4, verbose_name='P · 1 место (п. 10.3)')),
                ('p_second', models.DecimalField(decimal_places=2, default=1.15, max_digits=4, verbose_name='P · 2 место')),
                ('p_third', models.DecimalField(decimal_places=2, default=1.1, max_digits=4, verbose_name='P · 3 место')),
                ('min_rating', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Нижняя граница (п. 15.15)')),
                ('prize_mode', models.CharField(choices=[('match', 'P в формуле каждого матча (п. 9.2)'), ('tournament', 'P к итогу турнира (п. 10.6)'), ('none', 'Без коэффициента места')], default='match', max_length=16, verbose_name='Как применяется коэффициент места')),
                ('baseline', models.CharField(choices=[('sequential', 'Поматчево — как в примере п. 20'), ('pre_tournament', 'От рейтинга до турнира — как в п. 8.1')], default='sequential', max_length=16, verbose_name='База расчёта внутри турнира')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_params_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Коэффициенты рейтинга',
                'verbose_name_plural': 'Коэффициенты рейтинга',
            },
        ),
        migrations.CreateModel(
            name='RatingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('match', 'Матч'), ('no_show', 'Неявка без уважительной причины (п. 15.4–15.6)'), ('prize', 'Надбавка за призовое место (п. 10.6)'), ('correction', 'Исправление (п. 21.5–21.6)'), ('start', 'Стартовое значение (п. 6, 17)'), ('void', 'Аннулирование за неактивность (п. 18.4)')], default='match', max_length=12)),
                ('occurred_at', models.DateField(verbose_name='Дата')),
                ('score', models.CharField(blank=True, max_length=12, verbose_name='Счёт')),
                ('won', models.BooleanField(blank=True, null=True)),
                ('before', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Рейтинг до')),
                ('delta', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Изменение')),
                ('after', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Рейтинг после')),
                ('expected', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='E')),
                ('d', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='D')),
                ('k', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='K')),
                ('c', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='C')),
                ('p', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='P')),
                ('capped', models.BooleanField(default=False, verbose_name='Обрезано потолком (п. 12.1)')),
                ('transition', models.BooleanField(default=False, verbose_name='Переходный период (п. 11.2)')),
                ('reason', models.TextField(blank=True, verbose_name='Основание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reverted', models.BooleanField(default=False, verbose_name='Отменена')),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_entries_created', to=settings.AUTH_USER_MODEL)),
                ('group_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_entries', to='tournaments.groupmatch')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_entries', to='tournaments.match')),
                ('opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_entries_as_opponent', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='rating.ratingprofile')),
                ('reverted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_entries_reverted', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_entries', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Строка рейтинговой истории',
                'verbose_name_plural': 'Рейтинговая история',
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ratingprofile',
            index=models.Index(fields=['-value'], name='rating_rati_value_af1e38_idx'),
        ),
        migrations.AddIndex(
            model_name='ratingprofile',
            index=models.Index(fields=['status'], name='rating_rati_status_14c9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='ratingentry',
            index=models.Index(fields=['profile', '-occurred_at'], name='rating_rati_profile_8bfced_idx'),
        ),
        migrations.AddIndex(
            model_name='ratingentry',
            index=models.Index(fields=['tournament'], name='rating_rati_tournam_ecfbc5_idx'),
        ),
    ]
