# Generated by Django 4.2.15 on 2026-09-10 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер выпуска')),
                ('published_at', models.DateTimeField(verbose_name='Опубликован')),
                ('appeal_until', models.DateField(verbose_name='Приём апелляций до (п. 21.2)')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_editions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Выпуск рейтинга',
                'verbose_name_plural': 'Выпуски рейтинга',
                'ordering': ['-number'],
            },
        ),
        migrations.AlterField(
            model_name='ratingprofile',
            name='origin',
            field=models.CharField(choices=[('new', 'Новый спортсмен (п. 6.1)'), ('legacy', 'Перенос прежнего (п. 6.3)'), ('ittf', 'Из позиции ITTF (п. 17)')], default='new', max_length=10, verbose_name='Происхождение стартового значения'),
        ),
        migrations.CreateModel(
            name='RatingEditionRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveIntegerField(blank=True, null=True, verbose_name='Место')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Рейтинг')),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('no_matches', 'Нет матчей'), ('active', 'Активен'), ('inactive', 'Неактивен'), ('void', 'Рейтинг аннулирован')], max_length=12)),
                ('sex', models.CharField(blank=True, choices=[('m', 'Мужской'), ('f', 'Женский')], max_length=1)),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='rating.ratingedition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_edition_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Строка выпуска',
                'verbose_name_plural': 'Строки выпуска',
                'ordering': ['edition', 'place'],
                'unique_together': {('edition', 'user')},
            },
        ),
    ]
