# Generated by Django 4.2.15 on 2026-09-10 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rating', '0002_editions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(blank=True, max_length=120, verbose_name='Кто подал (п. 21.1)')),
                ('subject', models.TextField(verbose_name='Обжалуемое значение или действие')),
                ('circumstances', models.TextField(blank=True, verbose_name='Обстоятельства')),
                ('demand', models.TextField(verbose_name='Требование')),
                ('documents', models.TextField(blank=True, verbose_name='Документы')),
                ('received_at', models.DateField(verbose_name='Получена')),
                ('review_until', models.DateField(verbose_name='Рассмотреть до (п. 21.3)')),
                ('status', models.CharField(choices=[('pending', 'Ждёт решения'), ('upheld', 'Удовлетворена'), ('rejected', 'Отклонена')], default='pending', max_length=10)),
                ('decision', models.TextField(blank=True, verbose_name='Решение')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('correction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='rating.ratingentry')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_appeals_decided', to=settings.AUTH_USER_MODEL)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='rating.ratingedition')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_appeals_registered', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_appeals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Апелляция',
                'verbose_name_plural': 'Апелляции',
                'ordering': ['-received_at', '-id'],
            },
        ),
    ]
