# Generated by Django 4.2.15 on 2026-09-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_appeals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingentry',
            name='kind',
            field=models.CharField(choices=[('match', 'Матч'), ('no_show', 'Неявка без уважительной причины (п. 15.4–15.6)'), ('prize', 'Надбавка за призовое место (п. 10.6)'), ('correction', 'Исправление (п. 21.5–21.6)'), ('start', 'Стартовое значение (п. 6, 17)'), ('void', 'Аннулирование за неактивность (п. 18.4)'), ('merge', 'Объединение карточек (п. 5.3)')], default='match', max_length=12),
        ),
    ]
