# Generated by Django 4.2.15 on 2026-09-10 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_merge_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingedition',
            name='published_by',
        ),
        migrations.AlterUniqueTogether(
            name='ratingeditionrow',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ratingeditionrow',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='ratingeditionrow',
            name='user',
        ),
        migrations.DeleteModel(
            name='RatingAppeal',
        ),
        migrations.DeleteModel(
            name='RatingEdition',
        ),
        migrations.DeleteModel(
            name='RatingEditionRow',
        ),
    ]
