# Generated by Django 4.2.15 on 2026-09-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_remove_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
