# Generated by Django 4.2.15 on 2026-05-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.PositiveIntegerField(default=100, verbose_name='Рейтинг'),
        ),
    ]
