# Generated by Django 4.2.15 on 2026-09-10 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Эл. почта'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('gsk_chairman', 'Председатель Главной судейской коллегии')], max_length=32, verbose_name='Роль')),
                ('scope', models.CharField(choices=[('system', 'Система'), ('tournament', 'Турнир'), ('club', 'Клуб'), ('table', 'Стол')], default='system', max_length=16, verbose_name='Область')),
                ('scope_id', models.UUIDField(blank=True, null=True, verbose_name='Объект области')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_granted', to=settings.AUTH_USER_MODEL, verbose_name='Кем выдана')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'unique_together': {('user', 'kind', 'scope', 'scope_id')},
            },
        ),
    ]
